# Generated by Django 5.1.2 on 2024-11-01 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_producto_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagenes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='galeria',
            field=models.ManyToManyField(blank=True, null=True, to='productos.imagenes'),
        ),
    ]
